-- MySQL Script generated by MySQL Workbench
-- нд, 13-чер-2021 21:52:18 +0300
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema university
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema university
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `university` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `university` ;

-- -----------------------------------------------------
-- Table `university`.`themes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`themes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `theme_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `university`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `login` VARCHAR(15) NOT NULL,
  `password` CHAR(64) NOT NULL,
  `role` ENUM('TUTOR', 'ADMIN', 'STUDENT') NULL DEFAULT 'STUDENT',
  `is_blocked` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 91
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `university`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL COMMENT '\\n',
  `theme_id` INT NULL DEFAULT NULL,
  `tutor_id` INT NULL DEFAULT NULL,
  `description` VARCHAR(400) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_courses_course_themes_theme_id_idx` (`theme_id` ASC) VISIBLE,
  INDEX `fk_courses_users_tutor_id_user_id_idx` (`tutor_id` ASC) VISIBLE,
  CONSTRAINT `fk_courses_course_themes_theme_id`
    FOREIGN KEY (`theme_id`)
    REFERENCES `university`.`themes` (`id`),
  CONSTRAINT `fk_courses_users_tutor_id_user_id`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `university`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 119
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `university`.`students_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`students_courses` (
  `stud_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `mark` SMALLINT NULL DEFAULT NULL,
  PRIMARY KEY (`stud_id`, `course_id`),
  INDEX `fk_students_courses_1_idx` (`course_id` ASC) VISIBLE,
  INDEX `fk_students_courses_users_stud_id_user_id_idx` (`stud_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_courses_courses_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `university`.`courses` (`id`),
  CONSTRAINT `fk_students_courses_users_stud_id_user_id`
    FOREIGN KEY (`stud_id`)
    REFERENCES `university`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
